In [2]:
ls /home/jupyter/rw-migration-local/data/

20260216-final_dperession_df.parquet
20260216-final_insomnia_df.parquet
20260216-final_sleep_apnea_df.parquet
20260223-depression_diag_fb_dataset.joblib
20260223-final_dperession_df.parquet
20260305_final_sleep_level_df.parquet
20260308-final_depression_df.parquet
20260309-depression_diag_fb_dataset.joblib
20260316-depression_30day_features_dataset.joblib
20260316-depression_control_30day_features_dataset.joblib
20260316-final_dperession_control_30day_df.parquet
20260316-final_dperession_control_df.parquet
20260326_sleep_level_testset.parquet
20260326_sleep_level_trainset.parquet
20260416_final_sleep_daily_summary_with_sleep_efficiency_df.parquet
fitbit_sleep_daily_summary_pid_df.csv.gz
sleep_data_1000_df.csv.gz
sleep_data_1200_df.csv.gz
sleep_data_5000_df.csv.gz
sleep_data_{N}_df.csv.gz
sleep_vectors/


ls /home/jupyter/rw-migration-local/data/sleep_vectors/

### Reading the actual files

#### Testing one person

In [5]:
import numpy as np
import os
import pandas as pd

sleep_vectors_path = '/home/jupyter/rw-migration-local/data/sleep_vectors/'

single_vector = np.load(os.path.join(sleep_vectors_path, '1000107.npy'))
print(single_vector.shape)
print(single_vector)

(99, 24)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
import numpy as np
import os

sleep_vectors_path = '/home/jupyter/rw-migration-local/data/sleep_vectors/'

sleep_vectors = {}
failed = []

for filename in os.listdir(sleep_vectors_path):
    if filename.endswith('.npy'):
        participant_id = filename.replace('.npy', '')
        filepath = os.path.join(sleep_vectors_path, filename)
        try:
            sleep_vectors[participant_id] = np.load(filepath, allow_pickle=True)
        except Exception as e:
            failed.append(participant_id)

print(f"Loaded: {len(sleep_vectors)} vectors")
print(f"Failed: {len(failed)} vectors")

Loaded: 789 vectors
Failed: 1 vectors
