In [1]:
ls /home/jupyter/rw-migration-local/data/

20260216-final_dperession_df.parquet
20260216-final_insomnia_df.parquet
20260216-final_sleep_apnea_df.parquet
20260223-depression_diag_fb_dataset.joblib
20260223-final_dperession_df.parquet
20260305_final_sleep_level_df.parquet
20260308-final_depression_df.parquet
20260309-depression_diag_fb_dataset.joblib
20260316-depression_30day_features_dataset.joblib
20260316-depression_control_30day_features_dataset.joblib
20260316-final_dperession_control_30day_df.parquet
20260316-final_dperession_control_df.parquet
20260326_sleep_level_testset.parquet
20260326_sleep_level_trainset.parquet
20260416_final_sleep_daily_summary_with_sleep_efficiency_df.parquet
fitbit_sleep_daily_summary_pid_df.csv.gz
sleep_data_1000_df.csv.gz
sleep_data_1200_df.csv.gz
sleep_data_5000_df.csv.gz
sleep_data_{N}_df.csv.gz
sleep_vectors/


ls /home/jupyter/rw-migration-local/data/sleep_vectors/

### Reading the actual files

#### Testing one person

In [2]:
import numpy as np
import os
import pandas as pd

sleep_vectors_path = '/home/jupyter/rw-migration-local/data/sleep_vectors/'

single_vector = np.load(os.path.join(sleep_vectors_path, '1000107.npy'))
print(single_vector.shape)
print(single_vector)

(99, 24)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
import numpy as np
import os

sleep_vectors_path = '/home/jupyter/rw-migration-local/data/sleep_vectors/'

sleep_vectors = {}
failed = []

for filename in os.listdir(sleep_vectors_path):
    if filename.endswith('.npy'):
        participant_id = filename.replace('.npy', '')
        filepath = os.path.join(sleep_vectors_path, filename)
        try:
            sleep_vectors[participant_id] = np.load(filepath, allow_pickle=True)
        except Exception as e:
            failed.append(participant_id)

print(f"Loaded: {len(sleep_vectors)} vectors")
print(f"Failed: {len(failed)} vectors")

Loaded: 789 vectors
Failed: 1 vectors


##### this one failed vector had no data at all, so numpy wasn't able to load it in

In [4]:
!pip install git+https://github.com/amazon-science/chronos-forecasting.git


  Cloning https://github.com/amazon-science/chronos-forecasting.git to /tmp/pip-req-build-ijm68m7c
  Running command git clone --filter=blob:none --quiet https://github.com/amazon-science/chronos-forecasting.git /tmp/pip-req-build-ijm68m7c
  Resolved https://github.com/amazon-science/chronos-forecasting.git to commit 60e61d5c2698e61dc3689bdb14bf27bdb88d049b
  Installing build dependencies ... one
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Using cached transformers-4.57.6-py3-none-any.whl (12.0 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
  Attempting uninstall: huggingface_hu

In [5]:
!pip install momentfm

  Using cached huggingface_hub-0.24.0-py3-none-any.whl.metadata (13 kB)
  Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
  Using cached transformers-4.33.3-py3-none-any.whl.metadata (119 kB)
  Using cached tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Using cached huggingface_hub-0.24.0-py3-none-any.whl (419 kB)
Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached transformers-4.33.3-py3-none-any.whl (7.6 MB)
Using cached tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Atte

In [6]:
!pip install kneed

In [7]:
!pip install "numpy<2" --force-reinstall

  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chronos-forecasting 2.2.2 requires transformers<5,>=4.41, but you have transformers 4.33.3 which is incompatible.
gradio 5.49.1 requires huggingface-hub<2.0,>=0.33.5, but you have huggingface-hub 0.24.0 which is incompatible.
hail 0.2.135 requires numpy<3,>=2, but you have numpy 1.26.4 which is incompatible.
momentfm 0.1.4 requires numpy==1.25.2, but you have numpy 1.26.4 which is incompatible.
pandas-profiling 3.0.0 requires tangled-up-in-unicode==0.1.0, but you have ta

In [8]:
!pip install accelerate


In [9]:
!pip install "numpy==1.26.4" -q

In [10]:
import torch
import numpy as np
from chronos import ChronosPipeline

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
from kneed import KneeLocator
from momentfm import MOMENTPipeline

ImportError: /opt/conda/envs/jupyter/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommResume

In [ ]:
def plot_cluster_number_scores(X, k_min=1, k_max=10):
    inertia = []
    k_values = list(range(k_min, k_max + 1))

    for k in k_values:
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit_predict(X)
        inertia.append(kmeans.inertia_)

    plt.figure(figsize=(7, 5))
    plt.plot(k_values, inertia, 'bx-')
    plt.xlabel('Number of clusters')
    plt.ylabel('Inertia')
    plt.title('Elbow Method')
    plt.show()

    kl = KneeLocator(k_values, inertia, curve='convex', direction='decreasing')
    knee_k = kl.elbow
    print(f"Recommended k (elbow): {knee_k}")

    return {'k_values': k_values, 'inertia': inertia, 'knee_k': knee_k}
